using Hospital_system.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection.Emit;

namespace Hospital_system.Data
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder modelbuilder)
        {
            base.OnModelCreating(modelbuilder);


            //make id AutoGenerated in all entities
            foreach (var entityType in modelbuilder.Model.GetEntityTypes())
            {
                var idProp = entityType.FindProperty("Id");
                if (idProp != null && idProp.ClrType == typeof(string))
                {
                    idProp.SetDefaultValueSql("NEWID()");
                }
            }

            //Age Calculations
            modelbuilder.Entity<Patient>()
            .Property<int>("Age")
            .HasComputedColumnSql("DATEDIFF(YEAR, BirthDate, GETDATE())");
        }

        public DbSet<Patient> patients { get; set; }
        public DbSet<Doctor> doctors { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Department> departments { get; set; }
        public DbSet<ConsultationHour> consultationHours { get; set; }
    }
}
